In [6]:
import pandas as pd
import numpy as np
ufc = pd.read_csv("data.csv")
ufc.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [7]:
ufc = ufc[ufc.winner != 'no contest']
ufc = ufc[ufc.winner != 'draw']
ufc_zero = ufc.fillna(0)
ufc_zero.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        0.0   
1                                   0.0  ...                        0.0   
2                                   0.0  ...                        0.0   
3                                   0.0  ...                        0.0   
4                                   0.0  ...                        0.0   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               0.0                                    0.0   
1                               0.0                                    0.0   
2                               0.0                                    0.0   
3                               0.0                                    0.0   
4                               0.0                                    0.0   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      0.0                               0.0   
1                                      0.0                               0.0   
2                                      0.0                               0.0   
3                                      0.0                               0.0   
4                                      0.0                               0.0   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         0.0                              0.0   
1                         0.0                              0.0   
2                         0.0                              0.0   
3                         0.0                              0.0   
4                         0.0                              0.0   

   R__Round5_TIP_Standing Time   winby  winner  
0                          0.0     DEC     red  
1                          0.0     SUB    blue  
2                          0.0  KO/TKO     red  
3                          0.0     SUB    blue  
4                          0.0     DEC     red  

[5 rows x 895 columns]

In [8]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']
ufc_filtered = ufc_zero[idealcol].copy()

In [9]:
ufc_filtered["winner"]= ufc_filtered["winner"].replace("red", 0)
ufc_filtered["winner"]= ufc_filtered["winner"].replace("blue", 1)
ufc_filtered

BPrev  BStreak  B_Age  B_Height  B_Weight  RPrev  RStreak  R_Age  \
0         1        1   23.0     182.0        84      6        1   27.0   
1         0        0   32.0     175.0        70      0        0   29.0   
2         2        0   38.0     172.0        70      2        0   32.0   
3         0        0   23.0     170.0        56      6        4   25.0   
4         3        1   30.0     167.0        61      5        2   28.0   
...     ...      ...    ...       ...       ...    ...      ...    ...   
1472      0        0   26.0     172.0        61      0        0   27.0   
1473      2        1   26.0     165.0        56      3        0   31.0   
1474      3        2   36.0     187.0        93      1        1   27.0   
1475      3        1   31.0     167.0        52      4        0   34.0   
1476      2        1   31.0     187.0        84      1        1   37.0   

      R_Height  R_Weight  winner  
0          187        84       0  
1          182        70       1  
2          177        70       0  
3          175        56       1  
4          170        61       0  
...        ...       ...     ...  
1472       167        61       0  
1473       162        56       0  
1474       187        84       1  
1475       170        56       1  
1476       185        84       0  

[1451 rows x 11 columns]

In [10]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
X = ufc_filtered[feature_cols] # Features
y = ufc_filtered.winner # Target variable

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [12]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [13]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [14]:
from tensorflow.keras.utils import to_categorical

In [15]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [16]:
y_train_categorical

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [17]:
y_test_categorical

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=10, activation='relu', input_dim=10))
model.add(Dense(units=2, activation='softmax'))

In [27]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 22        
Total params: 132
Trainable params: 132
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100, # should be 100
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 3s - loss: 0.7240 - accuracy: 0.4867
Epoch 2/100
1015/1015 - 0s - loss: 0.6890 - accuracy: 0.5507
Epoch 3/100
1015/1015 - 0s - loss: 0.6748 - accuracy: 0.5783
Epoch 4/100
1015/1015 - 0s - loss: 0.6684 - accuracy: 0.6049
Epoch 5/100
1015/1015 - 0s - loss: 0.6653 - accuracy: 0.6059
Epoch 6/100
1015/1015 - 0s - loss: 0.6616 - accuracy: 0.6099
Epoch 7/100
1015/1015 - 0s - loss: 0.6593 - accuracy: 0.6118
Epoch 8/100
1015/1015 - 0s - loss: 0.6574 - accuracy: 0.6118
Epoch 9/100
1015/1015 - 0s - loss: 0.6560 - accuracy: 0.6118
Epoch 10/100
1015/1015 - 0s - loss: 0.6538 - accuracy: 0.6148
Epoch 11/100
1015/1015 - 0s - loss: 0.6524 - accuracy: 0.6167
Epoch 12/100
1015/1015 - 0s - loss: 0.6512 - accuracy: 0.6108
Epoch 13/100
1015/1015 - 0s - loss: 0.6500 - accuracy: 0.6118
Epoch 14/100
1015/1015 - 0s - loss: 0.6491 - accuracy: 0.6118
Epoch 15/100
1015/1015 - 0s - loss: 0.6483 - accuracy: 0.6167
Epoch 16/100
1015/1015 - 0s - loss: 0.6478 - accuracy: 0.

In [30]:
deep_model = Sequential()
deep_model.add(Dense(units=10, activation='relu', input_dim=10))
#deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [31]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=10,
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/10
1015/1015 - 3s - loss: 0.7067 - accuracy: 0.5360
Epoch 2/10
1015/1015 - 0s - loss: 0.6873 - accuracy: 0.5675
Epoch 3/10
1015/1015 - 0s - loss: 0.6781 - accuracy: 0.5833
Epoch 4/10
1015/1015 - 0s - loss: 0.6725 - accuracy: 0.5951
Epoch 5/10
1015/1015 - 1s - loss: 0.6680 - accuracy: 0.6049
Epoch 6/10
1015/1015 - 0s - loss: 0.6647 - accuracy: 0.6138
Epoch 7/10
1015/1015 - 0s - loss: 0.6617 - accuracy: 0.6118
Epoch 8/10
1015/1015 - 0s - loss: 0.6592 - accuracy: 0.6138
Epoch 9/10
1015/1015 - 0s - loss: 0.6571 - accuracy: 0.6177
Epoch 10/10
1015/1015 - 1s - loss: 0.6556 - accuracy: 0.6187


In [32]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 0s - loss: 0.6361 - accuracy: 0.5917
Normal Neural Network - Loss: 0.6772255268665629, Accuracy: 0.5917431116104126


In [33]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 1s - loss: 0.6653 - accuracy: 0.6055
Deep Neural Network - Loss: 0.6644799386689423, Accuracy: 0.60550457239151


In [34]:
ynew = model.predict(X_test_scaled)

In [35]:
ynew

array([[0.8468833 , 0.15311678],
       [0.7488588 , 0.25114116],
       [0.5300357 , 0.46996427],
       [0.843029  , 0.15697096],
       [0.6198829 , 0.38011706],
       [0.555842  , 0.44415808],
       [0.8654312 , 0.13456883],
       [0.79361486, 0.2063852 ],
       [0.7490186 , 0.2509813 ],
       [0.58421177, 0.41578826],
       [0.49562025, 0.50437975],
       [0.5461961 , 0.45380387],
       [0.45130572, 0.54869425],
       [0.8479561 , 0.15204392],
       [0.43220547, 0.5677945 ],
       [0.69649804, 0.30350193],
       [0.67250633, 0.32749367],
       [0.5619772 , 0.43802273],
       [0.5518324 , 0.44816765],
       [0.6211305 , 0.3788695 ],
       [0.5933024 , 0.40669754],
       [0.66207075, 0.33792925],
       [0.690528  , 0.309472  ],
       [0.38376358, 0.6162364 ],
       [0.56440544, 0.43559453],
       [0.79028034, 0.20971964],
       [0.7403103 , 0.2596897 ],
       [0.3850242 , 0.6149758 ],
       [0.32282498, 0.677175  ],
       [0.45291156, 0.54708844],
       [0.

In [36]:
y

0       0
1       1
2       0
3       1
4       0
       ..
1472    0
1473    0
1474    1
1475    1
1476    0
Name: winner, Length: 1451, dtype: int64

In [37]:
y_test.head()

1223    0
537     0
1111    1
597     1
38      0
Name: winner, dtype: int64

In [39]:
for i in range(len(X_test_scaled)):
    if np.round(ynew[i][0]) == 1:
        pred_win = 'blue'
    else:
        pred_win = 'red'
        
    print("X=%s, Predicted=%s" % (X_test_scaled[i], pred_win))

X=[-0.9264837  -0.62285573  1.42481016 -0.84085188 -0.83531737 -1.07800247
 -0.6495086   0.16159059 -0.83169539 -0.84453332], Predicted=blue
X=[ 1.18317632 -0.62285573  0.95281854 -0.84085188 -0.57019944  0.44027575
  1.08536305 -1.27085002 -0.6070325  -0.58164861], Predicted=blue
X=[ 1.18317632  0.34528909 -0.2271605   0.31154437  0.22515434 -1.07800247
 -0.6495086  -0.31588961  0.51628197  0.20700552], Predicted=blue
X=[ 0.12834631 -0.62285573  1.18881435 -0.26465376 -0.57019944 -1.07800247
 -0.6495086  -1.03210992 -0.6070325  -0.84453332], Predicted=blue
X=[-0.9264837  -0.62285573 -0.69915211 -0.61037263 -0.83531737 -1.07800247
 -0.6495086   0.6390708  -1.16868973 -0.84453332], Predicted=blue
X=[-0.9264837  -0.62285573 -1.40713954  0.31154437  0.22515434 -1.07800247
 -0.6495086  -1.27085002 -0.04537526  0.20700552], Predicted=blue
X=[-0.39906869 -0.62285573  1.89680177 -0.26465376  0.22515434  1.95855398
 -0.6495086   0.40033069 -0.27003816  0.66705377], Predicted=blue
X=[-0.9264837

 -0.6495086  -0.07714951 -0.6070325  -0.58164861], Predicted=blue
X=[-0.9264837  -0.62285573 -1.40713954  1.46394061  0.22515434  1.45246124
 -0.6495086  -0.55462972  0.85327631  0.20700552], Predicted=blue
X=[ 0.12834631  0.34528909 -0.4631563  -0.84085188 -0.57019944  0.9463685
 -0.6495086   0.8778109  -0.6070325  -0.58164861], Predicted=red
X=[-0.9264837  -0.62285573  1.89680177 -0.03417451  0.22515434 -0.06581699
 -0.6495086  -0.07714951 -0.27003816  0.20700552], Predicted=blue
X=[ 1.18317632  2.28157873 -0.2271605   0.54202361  0.22515434  0.9463685
  0.21792723  0.8778109   0.85327631  0.20700552], Predicted=red
X=[-0.9264837  -0.62285573  1.18881435  1.11822174  1.28562604 -1.07800247
 -0.6495086   1.5940312   0.29161908  1.25854437], Predicted=blue
X=[ 2.23800633  1.31343391 -1.87913115 -1.18657076 -1.16671478  1.95855398
 -0.6495086   0.40033069 -1.16868973 -1.17313921], Predicted=red
X=[ 1.18317632  1.31343391  0.48082693  0.88774249  1.28562604  0.9463685
  0.21792723  0.400

X=[ 0.12834631  1.31343391 -1.40713954 -0.61037263 -0.83531737  0.9463685
  2.8202347  -1.50959012 -0.83169539 -0.84453332], Predicted=blue
X=[ 0.65576131  2.28157873 -1.17114373 -0.61037263 -0.57019944 -0.57190973
  0.21792723 -1.03210992  0.29161908 -0.58164861], Predicted=red
X=[ 1.18317632  3.24972355 -0.2271605   1.46394061 -0.23880203  2.97073946
 -0.6495086  -1.03210992 -0.04537526 -0.25304272], Predicted=red
X=[-0.39906869 -0.62285573  0.95281854  2.96205574  2.74377464 -0.57190973
 -0.6495086   0.16159059  0.51628197  2.90157382], Predicted=blue
X=[ 0.12834631  1.31343391 -0.2271605   1.11822174  1.28562604 -0.06581699
  0.21792723 -1.27085002  0.51628197  0.66705377], Predicted=red
X=[ 1.18317632 -0.62285573 -0.2271605  -0.03417451 -0.23880203  1.95855398
 -0.6495086   0.16159059 -0.6070325  -0.25304272], Predicted=red
X=[-0.9264837  -0.62285573 -1.87913115  0.88774249  1.28562604 -0.06581699
  1.08536305 -0.31588961  1.41493354  1.25854437], Predicted=blue
X=[ 0.12834631  0.

In [41]:
y_test

1223    0
537     0
1111    1
597     1
38      0
       ..
231     0
1244    0
657     1
1146    0
535     0
Name: winner, Length: 436, dtype: int64

In [42]:
ynew

array([[0.8468833 , 0.15311678],
       [0.7488588 , 0.25114116],
       [0.5300357 , 0.46996427],
       [0.843029  , 0.15697096],
       [0.6198829 , 0.38011706],
       [0.555842  , 0.44415808],
       [0.8654312 , 0.13456883],
       [0.79361486, 0.2063852 ],
       [0.7490186 , 0.2509813 ],
       [0.58421177, 0.41578826],
       [0.49562025, 0.50437975],
       [0.5461961 , 0.45380387],
       [0.45130572, 0.54869425],
       [0.8479561 , 0.15204392],
       [0.43220547, 0.5677945 ],
       [0.69649804, 0.30350193],
       [0.67250633, 0.32749367],
       [0.5619772 , 0.43802273],
       [0.5518324 , 0.44816765],
       [0.6211305 , 0.3788695 ],
       [0.5933024 , 0.40669754],
       [0.66207075, 0.33792925],
       [0.690528  , 0.309472  ],
       [0.38376358, 0.6162364 ],
       [0.56440544, 0.43559453],
       [0.79028034, 0.20971964],
       [0.7403103 , 0.2596897 ],
       [0.3850242 , 0.6149758 ],
       [0.32282498, 0.677175  ],
       [0.45291156, 0.54708844],
       [0.

In [45]:
ynew_new = np.round(ynew)

In [53]:
yn = pd.DataFrame(ynew_new[:0])
yn

Empty DataFrame
Columns: [0, 1]
Index: []

In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test, ynew_new))

ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets