In [1]:
import pandas as pd
import numpy as np
ufc = pd.read_csv("resources\data.csv")
ufc.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [2]:
ufc.count()

BPrev                              1477
BStreak                            1477
B_Age                              1474
B_Height                           1476
B_HomeTown                         1471
                                   ... 
R__Round5_TIP_Neutral Time          144
R__Round5_TIP_Side Control Time     144
R__Round5_TIP_Standing Time         144
winby                              1461
winner                             1477
Length: 895, dtype: int64

In [3]:
ufc = ufc[ufc.winner != 'no contest']
ufc = ufc[ufc.winner != 'draw']
#ufc_zero = ufc.fillna(0)
ufc_zero = ufc.copy()
ufc_zero.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [4]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']
ufc_filtered = ufc_zero[idealcol].copy()

In [5]:
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("red", 0)
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("blue", 1)
#ufc_filtered

In [6]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1448
B_Height    1450
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1450
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [7]:
ufc_filtered['BPrev'] = ufc_filtered['BPrev'].fillna(np.mean(ufc_filtered['BPrev']))
ufc_filtered['BStreak'] = ufc_filtered['BStreak'].fillna(np.mean(ufc_filtered['BStreak']))
ufc_filtered['B_Age'] = ufc_filtered['B_Age'].fillna(np.mean(ufc_filtered['B_Age']))
ufc_filtered['B_Height'] = ufc_filtered['B_Height'].fillna(np.mean(ufc_filtered['B_Height']))
ufc_filtered['B_Weight'] = ufc_filtered['B_Weight'].fillna(np.mean(ufc_filtered['B_Weight']))
ufc_filtered['RPrev'] = ufc_filtered['RPrev'].fillna(np.mean(ufc_filtered['RPrev']))
ufc_filtered['RStreak'] = ufc_filtered['RStreak'].fillna(np.mean(ufc_filtered['RStreak']))
ufc_filtered['R_Age'] = ufc_filtered['R_Age'].fillna(np.mean(ufc_filtered['R_Age']))
ufc_filtered['R_Height'] = ufc_filtered['R_Height'].fillna(np.mean(ufc_filtered['R_Height']))
ufc_filtered['R_Weight'] = ufc_filtered['R_Weight'].fillna(np.mean(ufc_filtered['R_Weight']))

In [8]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1451
B_Height    1451
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1451
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [9]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
X = ufc_filtered[feature_cols] # Features
y = ufc_filtered.winner # Target variable

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [28]:
X_train.mean()

BPrev         1.756650
BStreak       0.643350
B_Age        31.023538
B_Height    177.296552
B_Weight     73.602956
RPrev         2.130049
RStreak       0.748768
R_Age        31.354059
R_Height    177.403941
R_Weight     73.850246
dtype: float64

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [12]:
le_y_train = le.transform(y_train)
le_y_train

array([1, 0, 1, ..., 1, 1, 0])

In [13]:
le_y_test = le.transform(y_test)
le_y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [14]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [15]:
X_scaler

In [16]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [17]:
X_train_scaled

In [18]:
from tensorflow.keras.utils import to_categorical

In [19]:
y_train_categorical = to_categorical(le_y_train)
y_test_categorical = to_categorical(le_y_test)

In [20]:
y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [21]:
y_test_categorical

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=10))
model.add(Dense(units=2, activation='softmax'))

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 66        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 14        
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [25]:
model.fit(
    X_train,
    y_train_categorical,
    epochs=100, # should be 100
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 1s - loss: 9.5438 - accuracy: 0.4079
Epoch 2/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 3/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 4/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 5/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 6/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 7/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 8/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 9/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 10/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 11/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 12/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 13/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 14/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 15/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.4079
Epoch 16/100
1015/1015 - 0s - loss: 9.5438 - accuracy: 0.

In [ ]:
model_json = model.to_json()
with open("model\model.json", "w") as json_file:
    json_file.write(model_json)

In [ ]:
# serialize weights to HDF5
model.save_weights("model\model.h5")

In [ ]:
# imports
import tensorflow as tf
import keras
from keras.models import model_from_json 

# opening and store file in a variable
json_file = open('model\model.json','r')
loaded_model_json = json_file.read()
json_file.close()

In [ ]:
# use Keras model_from_json to make a loaded model
loaded_model = tf.keras.models.model_from_json(loaded_model_json)

In [ ]:
# load weights into new model
loaded_model.load_weights("model\model.h5")
print("Awesome, your model has been loaded from disk! Cool beans!")

# compile and evaluate loaded model
loaded_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
X_train.head()

In [ ]:
deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=10))
#deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [ ]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

In [ ]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

In [27]:
ynew = model.predict(X_test)

In [ ]:
ynew

In [ ]:
y

In [ ]:
y_test.head()

In [ ]:
for i in range(len(X_test_scaled)):
    if np.round(ynew[i][0]) == 1:
        pred_win = 'blue'
    else:
        pred_win = 'red'
        
    print("X=%s, Predicted=%s" % (X_test_scaled[i], pred_win))

In [ ]:
y_test

In [ ]:
ynew

In [ ]:
ynew_new = np.round(ynew)

In [ ]:
yn = pd.DataFrame(ynew_new[:0])
yn

In [ ]:
#from sklearn.metrics import classification_report
#print(classification_report(y_test, ynew))