In [1]:
import pandas as pd
import numpy as np
ufc = pd.read_csv("resources\data.csv")
ufc.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [2]:
ufc.count()

BPrev                              1477
BStreak                            1477
B_Age                              1474
B_Height                           1476
B_HomeTown                         1471
                                   ... 
R__Round5_TIP_Neutral Time          144
R__Round5_TIP_Side Control Time     144
R__Round5_TIP_Standing Time         144
winby                              1461
winner                             1477
Length: 895, dtype: int64

In [3]:
ufc = ufc[ufc.winner != 'no contest']
ufc = ufc[ufc.winner != 'draw']
#ufc_zero = ufc.fillna(0)
ufc_zero = ufc.copy()
ufc_zero.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [4]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']
ufc_filtered = ufc_zero[idealcol].copy()

In [5]:
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("red", 0)
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("blue", 1)
#ufc_filtered

In [6]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1448
B_Height    1450
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1450
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [7]:
ufc_filtered['BPrev'] = ufc_filtered['BPrev'].fillna(np.mean(ufc_filtered['BPrev']))
ufc_filtered['BStreak'] = ufc_filtered['BStreak'].fillna(np.mean(ufc_filtered['BStreak']))
ufc_filtered['B_Age'] = ufc_filtered['B_Age'].fillna(np.mean(ufc_filtered['B_Age']))
ufc_filtered['B_Height'] = ufc_filtered['B_Height'].fillna(np.mean(ufc_filtered['B_Height']))
ufc_filtered['B_Weight'] = ufc_filtered['B_Weight'].fillna(np.mean(ufc_filtered['B_Weight']))
ufc_filtered['RPrev'] = ufc_filtered['RPrev'].fillna(np.mean(ufc_filtered['RPrev']))
ufc_filtered['RStreak'] = ufc_filtered['RStreak'].fillna(np.mean(ufc_filtered['RStreak']))
ufc_filtered['R_Age'] = ufc_filtered['R_Age'].fillna(np.mean(ufc_filtered['R_Age']))
ufc_filtered['R_Height'] = ufc_filtered['R_Height'].fillna(np.mean(ufc_filtered['R_Height']))
ufc_filtered['R_Weight'] = ufc_filtered['R_Weight'].fillna(np.mean(ufc_filtered['R_Weight']))

In [8]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1451
B_Height    1451
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1451
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [9]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
X = ufc_filtered[feature_cols] # Features
y = ufc_filtered.winner # Target variable

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [11]:
X_train.mean()

BPrev         1.756650
BStreak       0.643350
B_Age        31.023538
B_Height    177.296552
B_Weight     73.602956
RPrev         2.130049
RStreak       0.748768
R_Age        31.354059
R_Height    177.403941
R_Weight     73.850246
dtype: float64

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [13]:
le_y_train = le.transform(y_train)
le_y_train

array([1, 0, 1, ..., 1, 1, 0])

In [14]:
le_y_test = le.transform(y_test)
le_y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [15]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [16]:
X_scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [18]:
X_train_scaled[0]

array([-0.9264837 , -0.62285573,  1.74071869, -0.03417451, -0.23880203,
       -1.07800247, -0.6495086 ,  0.40425762, -0.27003816,  0.20700552])

In [19]:
from tensorflow.keras.utils import to_categorical

In [20]:
y_train_categorical = to_categorical(le_y_train)
y_test_categorical = to_categorical(le_y_test)

In [21]:
y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [22]:
y_test_categorical

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=10))
model.add(Dense(units=2, activation='softmax'))

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 66        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 14        
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [26]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100, # should be 100
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 3s - loss: 0.7803 - accuracy: 0.5714
Epoch 2/100
1015/1015 - 0s - loss: 0.7493 - accuracy: 0.5586
Epoch 3/100
1015/1015 - 0s - loss: 0.7282 - accuracy: 0.5586
Epoch 4/100
1015/1015 - 0s - loss: 0.7140 - accuracy: 0.5586
Epoch 5/100
1015/1015 - 0s - loss: 0.7041 - accuracy: 0.5596
Epoch 6/100
1015/1015 - 0s - loss: 0.6963 - accuracy: 0.5655
Epoch 7/100
1015/1015 - 0s - loss: 0.6904 - accuracy: 0.5685
Epoch 8/100
1015/1015 - 0s - loss: 0.6851 - accuracy: 0.5764
Epoch 9/100
1015/1015 - 0s - loss: 0.6809 - accuracy: 0.5793
Epoch 10/100
1015/1015 - 0s - loss: 0.6774 - accuracy: 0.5793
Epoch 11/100
1015/1015 - 0s - loss: 0.6742 - accuracy: 0.5773
Epoch 12/100
1015/1015 - 0s - loss: 0.6712 - accuracy: 0.5783
Epoch 13/100
1015/1015 - 0s - loss: 0.6690 - accuracy: 0.5872
Epoch 14/100
1015/1015 - 0s - loss: 0.6669 - accuracy: 0.5931
Epoch 15/100
1015/1015 - 0s - loss: 0.6645 - accuracy: 0.5931
Epoch 16/100
1015/1015 - 0s - loss: 0.6624 - accuracy: 0.

In [27]:
model_json = model.to_json()
with open("model\model.json", "w") as json_file:
    json_file.write(model_json)

In [28]:
# serialize weights to HDF5
model.save_weights("model\model.h5")

In [29]:
# imports
import tensorflow as tf
import keras
from keras.models import model_from_json 

# opening and store file in a variable
json_file = open('model\model.json','r')
loaded_model_json = json_file.read()
json_file.close()

Using TensorFlow backend.


In [30]:
# use Keras model_from_json to make a loaded model
loaded_model = tf.keras.models.model_from_json(loaded_model_json)

In [31]:
# load weights into new model
loaded_model.load_weights("model\model.h5")
print("Awesome, your model has been loaded from disk! Cool beans!")

# compile and evaluate loaded model
loaded_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Awesome, your model has been loaded from disk! Cool beans!


In [32]:
X_train.head()

BPrev  BStreak  B_Age  B_Height  B_Weight  RPrev  RStreak  R_Age  \
1057      0        0   38.0     177.0        70      0        0   33.0   
874       1        0   31.0     180.0        77      2        0   31.0   
1232      0        0   37.0     172.0        61      1        0   32.0   
498       0        0   30.0     162.0        52      1        1   29.0   
751       0        0   34.0     177.0        70      1        1   22.0   

      R_Height  R_Weight  
1057       175        77  
874        182        77  
1232       172        70  
498        162        52  
751        175        70

In [33]:
from pickle import dump

In [34]:
dump(X_scaler, open('model\scaler.pkl', 'wb'))

In [35]:
deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=10))
#deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [36]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 2s - loss: 0.7485 - accuracy: 0.4897
Epoch 2/100
1015/1015 - 0s - loss: 0.7241 - accuracy: 0.5222
Epoch 3/100
1015/1015 - 0s - loss: 0.7098 - accuracy: 0.5448
Epoch 4/100
1015/1015 - 0s - loss: 0.7007 - accuracy: 0.5468
Epoch 5/100
1015/1015 - 0s - loss: 0.6938 - accuracy: 0.5478
Epoch 6/100
1015/1015 - 0s - loss: 0.6885 - accuracy: 0.5557
Epoch 7/100
1015/1015 - 0s - loss: 0.6841 - accuracy: 0.5626
Epoch 8/100
1015/1015 - 0s - loss: 0.6805 - accuracy: 0.5675
Epoch 9/100
1015/1015 - 0s - loss: 0.6771 - accuracy: 0.5685
Epoch 10/100
1015/1015 - 0s - loss: 0.6746 - accuracy: 0.5734
Epoch 11/100
1015/1015 - 0s - loss: 0.6722 - accuracy: 0.5813
Epoch 12/100
1015/1015 - 0s - loss: 0.6700 - accuracy: 0.5833
Epoch 13/100
1015/1015 - 0s - loss: 0.6682 - accuracy: 0.5892
Epoch 14/100
1015/1015 - 0s - loss: 0.6666 - accuracy: 0.5911
Epoch 15/100
1015/1015 - 0s - loss: 0.6652 - accuracy: 0.5951
Epoch 16/100
1015/1015 - 0s - loss: 0.6640 - accuracy: 0.

In [37]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 1s - loss: 0.6547 - accuracy: 0.6009
Normal Neural Network - Loss: 0.6726643011110638, Accuracy: 0.6009174585342407


In [38]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 1s - loss: 0.6272 - accuracy: 0.5849
Deep Neural Network - Loss: 0.6792401797180876, Accuracy: 0.5848624110221863


In [39]:
ynew = model.predict(X_test_scaled)

In [40]:
ynew[0][0]

0.16115534

In [41]:
y

0        red
1       blue
2        red
3       blue
4        red
        ... 
1472     red
1473     red
1474    blue
1475    blue
1476     red
Name: winner, Length: 1451, dtype: object

In [42]:
y_test.head()

1223     red
537      red
1111    blue
597     blue
38       red
Name: winner, dtype: object

In [43]:
for i in range(len(X_test_scaled)):
    if np.round(ynew[i][0]) == 1:
        pred_win = 'blue'
    else:
        pred_win = 'red'
        
    print("X=%s, Predicted=%s" % (X_test_scaled[i], pred_win))

X=[-0.9264837  -0.62285573  1.49120559 -0.84085188 -0.83531737 -1.07800247
 -0.6495086   0.15864884 -0.83169539 -0.84453332], Predicted=red
X=[ 1.18317632 -0.62285573  0.9921794  -0.84085188 -0.57019944  0.44027575
  1.08536305 -1.31500384 -0.6070325  -0.58164861], Predicted=red
X=[ 1.18317632  0.34528909 -0.25538609  0.31154437  0.22515434 -1.07800247
 -0.6495086  -0.33256872  0.51628197  0.20700552], Predicted=blue
X=[ 0.12834631 -0.62285573  1.2416925  -0.26465376 -0.57019944 -1.07800247
 -0.6495086  -1.06939506 -0.6070325  -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573 -0.75441229 -0.61037263 -0.83531737 -1.07800247
 -0.6495086   0.64986639 -1.16868973 -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573 -1.50295158  0.31154437  0.22515434 -1.07800247
 -0.6495086  -1.31500384 -0.04537526  0.20700552], Predicted=red
X=[-0.39906869 -0.62285573  1.99023179 -0.26465376  0.22515434  1.95855398
 -0.6495086   0.40425762 -0.27003816  0.66705377], Predicted=red
X=[-0.9264837  -0.6

X=[-0.39906869 -0.62285573 -2.25149087 -1.41705001 -1.4318327  -0.06581699
 -0.6495086  -0.5781775  -0.83169539 -1.43602393], Predicted=blue
X=[-0.9264837  -0.62285573 -0.25538609 -1.18657076 -0.83531737 -1.07800247
 -0.6495086   0.15864884 -1.16868973 -0.84453332], Predicted=red
X=[-0.39906869 -0.62285573 -0.00587299  1.46394061  2.61121568  0.44027575
 -0.6495086  -1.31500384  1.41493354  2.31008322], Predicted=red
X=[-0.39906869  0.34528909 -0.75441229 -0.03417451 -0.57019944 -0.57190973
  0.21792723 -0.5781775  -0.83169539 -0.58164861], Predicted=red
X=[ 0.12834631 -0.62285573 -1.00392538  0.88774249  0.22515434 -0.06581699
 -0.6495086   0.15864884  0.51628197  0.20700552], Predicted=blue
X=[-0.39906869 -0.62285573 -0.25538609 -0.84085188 -0.83531737 -0.06581699
 -0.6495086   0.15864884 -1.39335262 -0.84453332], Predicted=red
X=[-0.39906869 -0.62285573 -0.50489919  0.31154437  0.68911071 -0.06581699
  0.21792723  0.64986639 -0.27003816  0.66705377], Predicted=red
X=[ 0.65576131  0.

X=[-0.9264837  -0.62285573 -1.75246468  0.31154437 -0.57019944 -0.06581699
  1.08536305 -1.56061262  0.29161908 -0.58164861], Predicted=red
X=[-0.9264837  -0.62285573 -0.75441229  0.88774249  0.68911071  0.44027575
  0.21792723 -0.82378628  1.41493354  0.66705377], Predicted=red
X=[-0.9264837  -0.62285573 -0.00587299  1.11822174  0.68911071 -1.07800247
 -0.6495086   1.63230151  0.85327631  0.66705377], Predicted=red
X=[ 0.12834631  0.34528909 -0.50489919  0.54202361  0.22515434 -0.57190973
  0.21792723  1.14108395  0.51628197  0.20700552], Predicted=blue
X=[-0.9264837  -0.62285573 -0.25538609 -0.03417451 -0.83531737 -0.06581699
  0.21792723 -1.31500384 -0.6070325  -0.84453332], Predicted=red
X=[ 0.65576131  2.28157873  1.99023179  0.54202361  0.68911071 -0.06581699
 -0.6495086   1.38669273  0.51628197  0.66705377], Predicted=red
X=[-0.39906869  0.34528909  0.9921794   0.54202361  0.22515434 -1.07800247
 -0.6495086   2.36912785 -0.04537526  0.20700552], Predicted=red
X=[ 4.34766634  1.3

In [44]:
y_test

1223     red
537      red
1111    blue
597     blue
38       red
        ... 
231      red
1244     red
657     blue
1146     red
535      red
Name: winner, Length: 436, dtype: object

In [45]:
ynew

array([[0.16115534, 0.83884466],
       [0.19597454, 0.8040255 ],
       [0.55842304, 0.44157696],
       [0.14709106, 0.8529089 ],
       [0.4285731 , 0.57142687],
       [0.44579437, 0.5542056 ],
       [0.24359776, 0.75640225],
       [0.19620617, 0.8037938 ],
       [0.16556072, 0.83443934],
       [0.54621136, 0.4537887 ],
       [0.4815745 , 0.51842546],
       [0.2553865 , 0.7446134 ],
       [0.5174518 , 0.4825482 ],
       [0.20319887, 0.79680115],
       [0.61682934, 0.38317063],
       [0.25755116, 0.74244887],
       [0.26300287, 0.7369971 ],
       [0.5322381 , 0.46776184],
       [0.41431424, 0.58568573],
       [0.32670063, 0.6732994 ],
       [0.55363005, 0.44636992],
       [0.29739705, 0.7026029 ],
       [0.3648443 , 0.63515574],
       [0.67629695, 0.32370305],
       [0.552305  , 0.44769505],
       [0.18804528, 0.8119547 ],
       [0.26375896, 0.73624104],
       [0.7867225 , 0.21327753],
       [0.53918   , 0.46081996],
       [0.48231354, 0.51768655],
       [0.

In [46]:
ynew_new = np.round(ynew)

In [47]:
yn = pd.DataFrame(ynew_new[:0])
yn

Empty DataFrame
Columns: [0, 1]
Index: []

In [48]:
#from sklearn.metrics import classification_report
#print(classification_report(y_test, ynew))