In [1]:
import pandas as pd
import numpy as np
ufc = pd.read_csv("data.csv")
ufc.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [2]:
ufc.count()

BPrev                              1477
BStreak                            1477
B_Age                              1474
B_Height                           1476
B_HomeTown                         1471
                                   ... 
R__Round5_TIP_Neutral Time          144
R__Round5_TIP_Side Control Time     144
R__Round5_TIP_Standing Time         144
winby                              1461
winner                             1477
Length: 895, dtype: int64

In [3]:
ufc = ufc[ufc.winner != 'no contest']
ufc = ufc[ufc.winner != 'draw']
#ufc_zero = ufc.fillna(0)
ufc_zero = ufc.copy()
ufc_zero.head()

BPrev  BStreak  B_Age  B_Height                          B_HomeTown  B_ID  \
0      1        1   23.0     182.0                        Trento Italy  2783   
1      0        0   32.0     175.0  Careiro da Várzea, Amazonas Brazil  2208   
2      2        0   38.0     172.0                      Kanagawa Japan   721   
3      0        0   23.0     170.0                      Tijuana Mexico  2825   
4      3        1   30.0     167.0                     Spokane, WA USA  2260   

          B_Location                 B_Name  B_Weight  \
0  Mezzocorona Italy         Marvin Vettori        84   
1   Pharr, Texas USA  Carlos Diego Ferreira        70   
2        Tokyo Japan          Takanori Gomi        70   
3     Tijuana Mexico         Brandon Moreno        56   
4    Spokane, WA USA     Elizabeth Phillips        61   

   B__Round1_Grappling_Reversals_Landed  ...  R__Round5_TIP_Ground Time  \
0                                   0.0  ...                        NaN   
1                                   NaN  ...                        NaN   
2                                   0.0  ...                        NaN   
3                                   NaN  ...                        NaN   
4                                   0.0  ...                        NaN   

   R__Round5_TIP_Guard Control Time  R__Round5_TIP_Half Guard Control Time  \
0                               NaN                                    NaN   
1                               NaN                                    NaN   
2                               NaN                                    NaN   
3                               NaN                                    NaN   
4                               NaN                                    NaN   

   R__Round5_TIP_Misc. Ground Control Time  R__Round5_TIP_Mount Control Time  \
0                                      NaN                               NaN   
1                                      NaN                               NaN   
2                                      NaN                               NaN   
3                                      NaN                               NaN   
4                                      NaN                               NaN   

   R__Round5_TIP_Neutral Time  R__Round5_TIP_Side Control Time  \
0                         NaN                              NaN   
1                         NaN                              NaN   
2                         NaN                              NaN   
3                         NaN                              NaN   
4                         NaN                              NaN   

   R__Round5_TIP_Standing Time   winby  winner  
0                          NaN     DEC     red  
1                          NaN     SUB    blue  
2                          NaN  KO/TKO     red  
3                          NaN     SUB    blue  
4                          NaN     DEC     red  

[5 rows x 895 columns]

In [4]:
idealcol = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight','winner']
ufc_filtered = ufc_zero[idealcol].copy()

In [5]:
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("red", 0)
#ufc_filtered["winner"]= ufc_filtered["winner"].replace("blue", 1)
#ufc_filtered

In [6]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1448
B_Height    1450
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1450
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [7]:
ufc_filtered['BPrev'] = ufc_filtered['BPrev'].fillna(np.mean(ufc_filtered['BPrev']))
ufc_filtered['BStreak'] = ufc_filtered['BStreak'].fillna(np.mean(ufc_filtered['BStreak']))
ufc_filtered['B_Age'] = ufc_filtered['B_Age'].fillna(np.mean(ufc_filtered['B_Age']))
ufc_filtered['B_Height'] = ufc_filtered['B_Height'].fillna(np.mean(ufc_filtered['B_Height']))
ufc_filtered['B_Weight'] = ufc_filtered['B_Weight'].fillna(np.mean(ufc_filtered['B_Weight']))
ufc_filtered['RPrev'] = ufc_filtered['RPrev'].fillna(np.mean(ufc_filtered['RPrev']))
ufc_filtered['RStreak'] = ufc_filtered['RStreak'].fillna(np.mean(ufc_filtered['RStreak']))
ufc_filtered['R_Age'] = ufc_filtered['R_Age'].fillna(np.mean(ufc_filtered['R_Age']))
ufc_filtered['R_Height'] = ufc_filtered['R_Height'].fillna(np.mean(ufc_filtered['R_Height']))
ufc_filtered['R_Weight'] = ufc_filtered['R_Weight'].fillna(np.mean(ufc_filtered['R_Weight']))

In [8]:
ufc_filtered.count()

BPrev       1451
BStreak     1451
B_Age       1451
B_Height    1451
B_Weight    1451
RPrev       1451
RStreak     1451
R_Age       1451
R_Height    1451
R_Weight    1451
winner      1451
dtype: int64

In [9]:
feature_cols = ['BPrev','BStreak','B_Age','B_Height','B_Weight','RPrev','RStreak','R_Age','R_Height','R_Weight']
X = ufc_filtered[feature_cols] # Features
y = ufc_filtered.winner # Target variable

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [12]:
le_y_train = le.transform(y_train)
le_y_train

array([1, 0, 1, ..., 1, 1, 0])

In [13]:
le_y_test = le.transform(y_test)
le_y_test

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,

In [14]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [15]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [16]:
from tensorflow.keras.utils import to_categorical

In [17]:
y_train_categorical = to_categorical(le_y_train)
y_test_categorical = to_categorical(le_y_test)

In [18]:
y_train_categorical

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [19]:
y_test_categorical

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=10))
model.add(Dense(units=2, activation='softmax'))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 66        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 14        
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [23]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100, # should be 100
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 5s - loss: 0.9153 - accuracy: 0.5931
Epoch 2/100
1015/1015 - 0s - loss: 0.8313 - accuracy: 0.5892
Epoch 3/100
1015/1015 - 0s - loss: 0.7763 - accuracy: 0.5882
Epoch 4/100
1015/1015 - 1s - loss: 0.7423 - accuracy: 0.5862
Epoch 5/100
1015/1015 - 0s - loss: 0.7209 - accuracy: 0.5882
Epoch 6/100
1015/1015 - 0s - loss: 0.7067 - accuracy: 0.5852
Epoch 7/100
1015/1015 - 0s - loss: 0.6950 - accuracy: 0.5852
Epoch 8/100
1015/1015 - 0s - loss: 0.6882 - accuracy: 0.5734
Epoch 9/100
1015/1015 - 0s - loss: 0.6819 - accuracy: 0.5685
Epoch 10/100
1015/1015 - 0s - loss: 0.6774 - accuracy: 0.5675
Epoch 11/100
1015/1015 - 0s - loss: 0.6742 - accuracy: 0.5655
Epoch 12/100
1015/1015 - 0s - loss: 0.6715 - accuracy: 0.5714
Epoch 13/100
1015/1015 - 0s - loss: 0.6691 - accuracy: 0.5704
Epoch 14/100
1015/1015 - 0s - loss: 0.6671 - accuracy: 0.5734
Epoch 15/100
1015/1015 - 0s - loss: 0.6652 - accuracy: 0.5754
Epoch 16/100
1015/1015 - 0s - loss: 0.6636 - accuracy: 0.

In [24]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

In [25]:
# serialize weights to HDF5
model.save_weights("model.h5")

In [26]:
# imports
import tensorflow as tf
import keras
from keras.models import model_from_json 

# opening and store file in a variable
json_file = open('model.json','r')
loaded_model_json = json_file.read()
json_file.close()

Using TensorFlow backend.


In [27]:
# use Keras model_from_json to make a loaded model
loaded_model = tf.keras.models.model_from_json(loaded_model_json)

In [28]:
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded Model from disk")

# compile and evaluate loaded model
loaded_model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

Loaded Model from disk


In [29]:
deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=10))
#deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [30]:
deep_model.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Train on 1015 samples
Epoch 1/100
1015/1015 - 13s - loss: 0.8219 - accuracy: 0.5123
Epoch 2/100
1015/1015 - 0s - loss: 0.7750 - accuracy: 0.5300
Epoch 3/100
1015/1015 - 0s - loss: 0.7435 - accuracy: 0.5458
Epoch 4/100
1015/1015 - 1s - loss: 0.7220 - accuracy: 0.5606
Epoch 5/100
1015/1015 - 0s - loss: 0.7078 - accuracy: 0.5655
Epoch 6/100
1015/1015 - 0s - loss: 0.6978 - accuracy: 0.5635
Epoch 7/100
1015/1015 - 0s - loss: 0.6888 - accuracy: 0.5685
Epoch 8/100
1015/1015 - 0s - loss: 0.6833 - accuracy: 0.5783
Epoch 9/100
1015/1015 - 0s - loss: 0.6775 - accuracy: 0.5823
Epoch 10/100
1015/1015 - 0s - loss: 0.6738 - accuracy: 0.5823
Epoch 11/100
1015/1015 - 1s - loss: 0.6697 - accuracy: 0.5882
Epoch 12/100
1015/1015 - 0s - loss: 0.6661 - accuracy: 0.5901
Epoch 13/100
1015/1015 - 1s - loss: 0.6632 - accuracy: 0.6049
Epoch 14/100
1015/1015 - 0s - loss: 0.6609 - accuracy: 0.6099
Epoch 15/100
1015/1015 - 0s - loss: 0.6585 - accuracy: 0.6099
Epoch 16/100
1015/1015 - 0s - loss: 0.6568 - accuracy: 0

In [31]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 3s - loss: 0.6524 - accuracy: 0.6009
Normal Neural Network - Loss: 0.6784701227048121, Accuracy: 0.6009174585342407


In [32]:
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

436/1 - 2s - loss: 0.6471 - accuracy: 0.6009
Deep Neural Network - Loss: 0.6834031075512598, Accuracy: 0.6009174585342407


In [33]:
ynew = model.predict(X_test_scaled)

In [34]:
ynew

array([[0.17313807, 0.826862  ],
       [0.16684724, 0.8331527 ],
       [0.51364   , 0.48636004],
       [0.27115548, 0.72884446],
       [0.37701684, 0.62298316],
       [0.41891104, 0.5810889 ],
       [0.17795937, 0.8220407 ],
       [0.3410175 , 0.6589825 ],
       [0.18934874, 0.81065124],
       [0.6073475 , 0.3926525 ],
       [0.41118518, 0.58881485],
       [0.3673943 , 0.6326057 ],
       [0.55650085, 0.44349918],
       [0.22559376, 0.7744063 ],
       [0.58724636, 0.4127536 ],
       [0.2969325 , 0.7030675 ],
       [0.25681734, 0.74318266],
       [0.3680106 , 0.6319894 ],
       [0.46104068, 0.5389593 ],
       [0.38501278, 0.6149872 ],
       [0.49022055, 0.5097794 ],
       [0.33905292, 0.66094714],
       [0.3249736 , 0.6750263 ],
       [0.72058797, 0.27941203],
       [0.4857149 , 0.514285  ],
       [0.16023122, 0.83976877],
       [0.49022055, 0.5097794 ],
       [0.5524092 , 0.44759083],
       [0.48416016, 0.5158399 ],
       [0.5312345 , 0.46876553],
       [0.

In [35]:
y

0        red
1       blue
2        red
3       blue
4        red
        ... 
1472     red
1473     red
1474    blue
1475    blue
1476     red
Name: winner, Length: 1451, dtype: object

In [36]:
y_test.head()

1223     red
537      red
1111    blue
597     blue
38       red
Name: winner, dtype: object

In [37]:
for i in range(len(X_test_scaled)):
    if np.round(ynew[i][0]) == 1:
        pred_win = 'blue'
    else:
        pred_win = 'red'
        
    print("X=%s, Predicted=%s" % (X_test_scaled[i], pred_win))

X=[-0.9264837  -0.62285573  1.49120559 -0.84085188 -0.83531737 -1.07800247
 -0.6495086   0.15864884 -0.83169539 -0.84453332], Predicted=red
X=[ 1.18317632 -0.62285573  0.9921794  -0.84085188 -0.57019944  0.44027575
  1.08536305 -1.31500384 -0.6070325  -0.58164861], Predicted=red
X=[ 1.18317632  0.34528909 -0.25538609  0.31154437  0.22515434 -1.07800247
 -0.6495086  -0.33256872  0.51628197  0.20700552], Predicted=blue
X=[ 0.12834631 -0.62285573  1.2416925  -0.26465376 -0.57019944 -1.07800247
 -0.6495086  -1.06939506 -0.6070325  -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573 -0.75441229 -0.61037263 -0.83531737 -1.07800247
 -0.6495086   0.64986639 -1.16868973 -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573 -1.50295158  0.31154437  0.22515434 -1.07800247
 -0.6495086  -1.31500384 -0.04537526  0.20700552], Predicted=red
X=[-0.39906869 -0.62285573  1.99023179 -0.26465376  0.22515434  1.95855398
 -0.6495086   0.40425762 -0.27003816  0.66705377], Predicted=red
X=[-0.9264837  -0.6

 -0.6495086  -1.06939506 -0.83169539 -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573  0.2436401  -0.26465376 -0.23880203  3.4768322
  0.21792723 -1.06939506 -0.04537526 -0.25304272], Predicted=red
X=[-0.9264837  -0.62285573  1.49120559  1.11822174  2.34609775 -1.07800247
 -0.6495086   0.64986639  1.75192788  2.31008322], Predicted=red
X=[-0.9264837  -0.62285573  1.74071869  1.46394061  1.28562604 -0.57190973
  0.21792723 -1.06939506  1.41493354  1.25854437], Predicted=red
X=[-0.39906869 -0.62285573 -0.00587299  0.54202361  0.22515434  0.44027575
 -0.6495086  -0.33256872 -0.04537526 -0.25304272], Predicted=red
X=[ 0.12834631  1.31343391 -0.25538609 -1.18657076 -0.57019944 -0.06581699
  0.21792723  0.64986639 -0.6070325  -0.58164861], Predicted=blue
X=[-0.9264837  -0.62285573  0.7426663  -0.26465376 -0.83531737 -1.07800247
 -0.6495086  -0.08695994 -1.39335262 -0.84453332], Predicted=red
X=[-0.9264837  -0.62285573 -0.00587299  0.88774249 -0.23880203  0.44027575
  1.95279888 -0.5781

In [38]:
y_test

1223     red
537      red
1111    blue
597     blue
38       red
        ... 
231      red
1244     red
657     blue
1146     red
535      red
Name: winner, Length: 436, dtype: object

In [39]:
ynew

array([[0.17313807, 0.826862  ],
       [0.16684724, 0.8331527 ],
       [0.51364   , 0.48636004],
       [0.27115548, 0.72884446],
       [0.37701684, 0.62298316],
       [0.41891104, 0.5810889 ],
       [0.17795937, 0.8220407 ],
       [0.3410175 , 0.6589825 ],
       [0.18934874, 0.81065124],
       [0.6073475 , 0.3926525 ],
       [0.41118518, 0.58881485],
       [0.3673943 , 0.6326057 ],
       [0.55650085, 0.44349918],
       [0.22559376, 0.7744063 ],
       [0.58724636, 0.4127536 ],
       [0.2969325 , 0.7030675 ],
       [0.25681734, 0.74318266],
       [0.3680106 , 0.6319894 ],
       [0.46104068, 0.5389593 ],
       [0.38501278, 0.6149872 ],
       [0.49022055, 0.5097794 ],
       [0.33905292, 0.66094714],
       [0.3249736 , 0.6750263 ],
       [0.72058797, 0.27941203],
       [0.4857149 , 0.514285  ],
       [0.16023122, 0.83976877],
       [0.49022055, 0.5097794 ],
       [0.5524092 , 0.44759083],
       [0.48416016, 0.5158399 ],
       [0.5312345 , 0.46876553],
       [0.

In [40]:
ynew_new = np.round(ynew)

In [41]:
yn = pd.DataFrame(ynew_new[:0])
yn

Empty DataFrame
Columns: [0, 1]
Index: []

In [42]:
from sklearn.metrics import classification_report
print(classification_report(y_test, ynew))

ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets